site_name: DevCraft Документации
repo_url: https://github.com/Gokujo/mhdocs
repo_name: Gokujo/mhdocs
edit_uri: edit/main/docs/
site_url: https://readme.devcraft.club
site_author: Maxim Harder
site_description: "Сайт с документациями, который построен на Python и системе MKDocs. Исходники всегда будут доступны на GitHub."
copyright: "Документация защищена лицензией <a href='https://github.com/Gokujo/mhdocs/blob/master/LICENSE.md'>MIT license</a>"

nav:
    - Главная: index.md
    - Пользование сайтом:
          - Как покупать: site/how-to-buy.md
          - Тех. Поддержка: site/how-to-ask-for-support.md
    - Бесплатные разработки:
          - Telegram Posting:
                - Установка: dev/telegramposting/install.md
                - Настройка бота: dev/telegramposting/bot.md
                - Версии изменениий: dev/telegramposting/changelog.md
          - MyStatus: dev/mystatus.md
          - Release Status: dev/releasestatus.md
          - Schema.Org: dev/schema.md
          - Пользовательские теги: dev/usertags.md
          - Webmaster Verification: dev/webmaster-verification.md
          - XF Lists: dev/xflist.md
          - XF Select: dev/xfselect.md
    - Хаки:
          - Страницы как на КиноПоиске: dev/hook-pages-like-kp.md
          - Подсчёт символов в короткой новости: dev/hook-shortstory-signs-count.md
    - Платные разработки:
          - Шаблон SeasonVar:
                - Установка: dev/paid-seasonvar/install.md
                - Automatic Related: dev/paid-seasonvar/related.md
                - F.A.Q.: dev/paid-seasonvar/faq.md
          - Курс валют: dev/paid-currencies_rate.md
          - Последние новости списком: dev/paid-lastnews.md

theme:
    name: material
    colorscheme: monokai
    language: ru
    features:
        - content.code.annotate
        - navigation.instant
        - navigation.tracking
#        - navigation.tabs
#        - navigation.tabs.sticky
        - navigation.sections
        - toc.follow
        - navigation.top
    palette:
        primary: indigo

plugins:
    - git-revision-date
    - git-revision-date-localized:
        enable_creation_date: true
    - tags
    - search:
          lang:
            - ru
            - de
            - en
    - minify:
        minify_html: true
        minify_js: true
        minify_css: true
        htmlmin_opts:
            remove_comments: true
    -   redirects:
            redirect_maps:
                'dev/paid-seasonvar/00_install.md': 'dev/paid-seasonvar/install.md'
                'dev/paid-seasonvar/01_related.md': 'dev/paid-seasonvar/related.md'
                'dev/paid-seasonvar/02_faq.md': 'dev/paid-seasonvar/faq.md'
                'dev/telegramposting/00_install.md': 'dev/telegramposting/install.md'
                'dev/telegramposting/01_changelog.md': 'dev/telegramposting/changelog.md'

markdown_extensions:
    - abbr
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.highlight:
        linenums: true
        anchor_linenums: true
        use_pygments: true
        auto_title: true
#    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - tables
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - md_in_html

extra:
    homepage: https://devcraft.club
    analytics:
        provider: google
        property: G-6B531VYCBD
    version:
        provider: mike
    generator: false
    social:
        - icon: fontawesome/solid/paper-plane
          link: https://t.me/maharder
          name: Telegram

extra_css:
  - extras/css/all.min.css
  - extras/css/styles.css