site_name: DevCraft Документации
repo_url: https://github.com/DevCraftClub/mhdocs
repo_name: DevCraftClub/mhdocs
edit_uri: edit/main/docs/
site_url: https://readme.devcraft.club
site_author: Maxim Harder
site_description: "Сайт с документациями, который построен на Python и системе MKDocs. Исходники всегда будут доступны на GitHub."
copyright: "Документация защищена лицензией <a href='https://github.com/DevCraftClub/mhdocs/blob/master/LICENSE.md'>MIT license</a>"

nav:
    -   Главная: index.md
    -   Пользование сайтом:
            -   Как покупать: site/how-to-buy.md
            -   Тех. Поддержка: site/how-to-ask-for-support.md
    -   Инструкции:
            -   Composer: dev/composer.md
            -   Crowdin: dev/crowdin.md
    -   Бесплатные разработки:
            -   DLE Faker:
                    -   Установка: dev/dle_faker/install.md
                    -   Настройка: dev/dle_faker/settings.md
                    -   Теги для оформления шаблонов:
                            -   Общие: dev/dle_faker/tag_for_all.md
                            -   Для пользователей: dev/dle_faker/tag_for_users.md
                            -   Пля новостей: dev/dle_faker/tag_for_news.md
                    -   Генератор:
                            -   Генерация пользователей: dev/dle_faker/gen_users.md
                            -   Генерация новостей: dev/dle_faker/gen_news.md
                    -   Функционал парсера данных: dev/dle_faker/parser.md
                    -   История изменений: dev/dle_faker/changelog.md
            -   Telegram Posting:
                    -   Установка: dev/telegramposting/install.md
                    -   Подключение в сторонние разработки: dev/telegramposting/custom_add.md
                    -   Теги для оформления шаблонов: dev/telegramposting/template_tags.md
                    -   Настройка бота: dev/telegramposting/bot.md
                    -   Версии изменений: dev/telegramposting/changelog.md
            -   MH Admin:
                    -   Установка: dev/mhadmin/install.md
                    -   Для пользователей:
                            -   Настройка: dev/mhadmin/frontend/manage.md
                    -   Для разработчиков:
                            -   Генератор модулей: dev/mhadmin/new_module.md
                            -   Главный файл в папке inc: dev/mhadmin/backend/inc_main.md
                            -   Модуль главной страницы: dev/mhadmin/backend/module.md
                            -   Генератор языковых файлов: dev/mhadmin/generate_languages.md
                            -   Back-End:
                                    -   Главная: dev/mhadmin/backend/index.md
                                    -   База данных:
                                            -   BasisModel: dev/mhadmin/backend/classes/BasisModel.md
                                            -   BasisRepository: dev/mhadmin/backend/classes/BasisRepository.md
                                            -   MhDB: dev/mhadmin/backend/classes/MhDB.md
                                    -   Классы:
                                            -   Admin: dev/mhadmin/backend/classes/Admin.md
                                            -   CacheControl: dev/mhadmin/backend/classes/CacheControl.md
                                            -   ComposerAction: dev/mhadmin/backend/classes/ComposerAction.md
                                            -   DataManager: dev/mhadmin/backend/classes/DataManager.md
                                            -   LogGenerator: dev/mhadmin/backend/classes/LogGenerator.md
                                            -   MhAjax: dev/mhadmin/backend/classes/MhAjax.md
                                            -   MhLog: dev/mhadmin/backend/classes/MhLog.md
                                            -   MhLogRepository: dev/mhadmin/backend/classes/MhLogRepository.md
                                            -   MhTranslation: dev/mhadmin/backend/classes/MhTranslation.md
                                            -   TwigFilter: dev/mhadmin/backend/classes/TwigFilter.md
                                    -   Ответы на запросы AJAX:
                                            -   AjaxAbstractResponse: dev/mhadmin/backend/classes/AjaxAbstractResponse.md
                                            -   ErrorResponseAjax: dev/mhadmin/backend/classes/ErrorResponseAjax.md
                                            -   SuccessResponseAjax: dev/mhadmin/backend/classes/SuccessResponseAjax.md
                                    -   Твиг (Twig) дополнения:
                                            -   AdminUrlExtension: dev/mhadmin/backend/classes/AdminUrlExtension.md
                                            -   DateTimeFormatter: dev/mhadmin/backend/classes/DateTimeFormatter.md
                                            -   DeclineExtension: dev/mhadmin/backend/classes/DeclineExtension.md
                                            -   MobileDetectExtension: dev/mhadmin/backend/classes/MobileDetectExtension.md
                                            -   TextLimiter: dev/mhadmin/backend/classes/TextLimiter.md
                                    -   Типы:
                                            -   AdminLink: dev/mhadmin/backend/classes/AdminLink.md
                                            -   Author: dev/mhadmin/backend/classes/Author.md
                                            -   BreadCrumb: dev/mhadmin/backend/classes/BreadCrumb.md
                                    -   Трейты:
                                            -   AssetsChecker: dev/mhadmin/backend/classes/AssetsChecker.md
                                            -   DataLoader: dev/mhadmin/backend/classes/DataLoader.md
                                            -   DleData: dev/mhadmin/backend/classes/DleData.md
                                            -   UpdatesChecker: dev/mhadmin/backend/classes/UpdatesChecker.md
                            -   Front-End:
                                    -   Шаблоны: dev/mhadmin/frontend/templates.md
                    -   История изменений: dev/mhadmin/changelog.md
            -   MyStatus: dev/mystatus.md
            -   Release Status: dev/releasestatus.md
            -   Schema.Org: dev/schema.md
            -   Пользовательские теги: dev/usertags.md
            -   Webmaster Verification: dev/webmaster-verification.md
            -   XF Lists: dev/xflist.md
            -   XF Select: dev/xfselect.md
    -   Хаки:
            -   Страницы как на КиноПоиске: dev/hook-pages-like-kp.md
            -   Подсчёт символов в короткой новости: dev/hook-shortstory-signs-count.md
    -   Платные разработки:
            -   Шаблон SeasonVar:
                    -   Установка: dev/paid-seasonvar/install.md
                    -   Automatic Related: dev/paid-seasonvar/related.md
                    -   F.A.Q.: dev/paid-seasonvar/faq.md
            -   Курс валют: dev/paid-currencies_rate.md
            -   Последние новости списком: dev/paid-lastnews.md

theme:
    name: material
    colorscheme: monokai
    language: ru
    features:
        - content.code.annotate
        - navigation.instant
        - navigation.tracking
        #        - navigation.tabs
        #        - navigation.tabs.sticky
        - navigation.sections
        - toc.follow
        - navigation.top
    palette:
        primary: indigo

plugins:
    -   git-revision-date
    -   git-revision-date-localized:
            enable_creation_date: true
    -   tags
    -   search:
            lang:
                - ru
                - de
                - en
    -   autorefs:
            resolve_closest: true
    -   minify:
            minify_html: true
            minify_js: true
            minify_css: true
            htmlmin_opts:
                remove_comments: true
    -   redirects:
            redirect_maps:
                'dev/paid-seasonvar/00_install.md': 'dev/paid-seasonvar/install.md'
                'dev/paid-seasonvar/01_related.md': 'dev/paid-seasonvar/related.md'
                'dev/paid-seasonvar/02_faq.md': 'dev/paid-seasonvar/faq.md'
                'dev/telegramposting/00_install.md': 'dev/telegramposting/install.md'
                'dev/telegramposting/01_changelog.md': 'dev/telegramposting/changelog.md'

markdown_extensions:
    - abbr
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.highlight:
            linenums: true
            anchor_linenums: true
            use_pygments: true
            auto_title: true
    #    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
            alternate_style: true
    - tables
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - md_in_html

extra:
    homepage: https://devcraft.club
    analytics:
        provider: google
        property: G-6B531VYCBD
    version:
        provider: mike
    generator: false
    social:
        -   icon: fontawesome/solid/paper-plane
            link: https://t.me/maharder
            name: Telegram

extra_css:
    - extras/css/all.min.css
    - extras/css/styles.css