site_name: DevCraft Документации
repo_url: https://github.com/DevCraftClub/mhdocs
repo_name: DevCraftClub/mhdocs
edit_uri: edit/main/docs/
site_url: https://readme.devcraft.club
site_author: Maxim Harder
site_description: "Сайт с документациями, который построен на Python и системе MKDocs. Исходники всегда будут доступны на GitHub."
copyright: "Документация защищена лицензией <a href='https://github.com/DevCraftClub/mhdocs/blob/master/LICENSE.md'>MIT license</a>"

# Навигация автоматически генерируется плагином awesome-nav
# на основе структуры папок в docs/
# Для кастомизации можно использовать файлы .nav.yml в папках

theme:
  name: material
  colorscheme: monokai
  language: ru
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.tracking
    #        - navigation.tabs
    #        - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
  palette:
    primary: indigo
  consent:
    title: Cookie сайта
    description: > # (1)
      Мы используем файлы cookie для распознавания ваших повторных посещений и предпочтений, а также
      для оценки эффективности нашей документации и того, находят ли пользователи
      то, что ищут. Давая своё согласие, вы помогаете нам
      улучшать нашу документацию.

plugins:
  - search:
      lang:
        - ru
        - de
        - en
      separator: '[\s\-,:!=\[\]()"/]+'
  - localsearch
  - exclude
  - exclude-search
  - git-revision-date
  - tags
  - autorefs:
      resolve_closest: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - redirects:
      redirect_maps:
        "dev/paid-seasonvar/00_install.md": "dev/paid-seasonvar/install.md"
        "dev/paid-seasonvar/01_related.md": "dev/paid-seasonvar/related.md"
        "dev/paid-seasonvar/02_faq.md": "dev/paid-seasonvar/faq.md"
        "dev/telegramposting/00_install.md": "dev/telegramposting/install.md"
        "dev/telegramposting/01_changelog.md": "dev/telegramposting/changelog.md"
  - awesome-nav
  - section-index
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Europe/Berlin
  - autolinks
  - mermaid2
  - glightbox:
      touchNavigation: true
      loop: true
  - import-statement
  - meta-manager
  - git-authors:
      show_email_address: false
      show_contribution: true
      add_co_authors: true
      ignore_authors:
        - m.harder@bsg.de
  - htmlproofer
  - link-marker
  - neoteroi.mkdocsoad:
      use_pymdownx: true

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - markdown_version_annotations:
      version_added_title: "\\1: Добавлен новый функционал"
      version_changed_title: "\\1: Изменения в существующем функционале"
      version_removed_title: "\\1: Удаление функционала или очистка проекта"
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      use_pygments: true
      auto_title: true
  #    - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3

extra:
  homepage: https://devcraft.club
  analytics:
    provider: google
    property: G-6B531VYCBD
  version:
    provider: mike
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: https://t.me/maharder
      name: Telegram

  search_metadata_file: docs/search-metadata.yml
  search_synonyms: true
  search_categories: true
  search_weights: true

extra_javascript:
  - extras/js/search-metadata-loader.js
  - extras/js/search-enhancement.js

extra_css:
  - extras/css/all.min.css
  - extras/css/search-enhancement.css
  - extras/css/styles.css
