title: Ошибки
nav:
  - ForbiddenErrorResponseDto: ForbiddenErrorResponseDto.md
  - NotFoundErrorResponseDto: NotFoundErrorResponseDto.md
  - UnauthorizedErrorResponseDto: UnauthorizedErrorResponseDto.md 