title: TagsAdd
nav:
  - Начало работы: getting_started.md
  - Установка: install.md
  - Настройки: settings.md
  - Гайды:
      - Подключение в теме: guides/theme.md
  - История изменений: changelog.md
