title: DevCraft Admin
nav:
  - Начало работы: getting_started.md
  - Установка: install.md
  - Миграция на 200.х.х: migration.md
  - Гайды:
      - Настройка: guides/manage.md
      - Создание CRUD-страницы: guides/crud_pages.md
      - Примеры Form: guides/form_examples.md
      - Генератор модулей: guides/new_module.md
      - Генератор языковых файлов: guides/generate_languages.md
      - ИИ-инструменты: guides/ai_tools.md
  - Справочник:
      - Front-End: reference/front-end/
      - Back-End: reference/back-end/
  - История изменений: changelog.md
