title: Разработки
nav:
  - API Wrappers:
      - KinopoiskUnoffical PHP: api_wrappers/notkinopoiskphp/
      - KinopoiskDev PHP: api_wrappers/kinopoiskdev/
  - Бесплатные разработки:
      - DB Manager: dle/db_manager/
      - "Re: Post": dle/repost/
      - DLE Faker: dle/dle_faker/
      - DLE API: dle/dle_api/
      - DevCraft Admin: dle/devcraft_admin/
      - Пользовательские теги: dle/usertags/
      - MyStatus: dle/mystatus.md
      - Release Status: dle/releasestatus.md
  - Хаки и простые модули:
      - Schema.Org: dle/simple/schema.md
      - Webmaster Verification: dle/simple/webmaster-verification.md
      - XF Lists: dle/simple/xflist.md
      - XF Select: dle/simple/xfselect.md
      - Страницы как на КиноПоиске: dle/simple/hook-pages-like-kp.md
      - Подсчёт символов в короткой новости: dle/simple/hook-shortstory-signs-count.md
  - Платные разработки:
      - Курс валют: dle/paid-currencies_rate.md
