name: Деплой документации

on:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование кода
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Настройка Git
        run: |
          git config user.name github-actions[bot]
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Определение версии из manifest.json
        id: version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          if [[ -z "$VERSION" || "$VERSION" == "null" ]]; then
            echo "В manifest.json отсутствует корректное поле version" >&2
            
            VERSION="dev"
          fi
          echo "version=$VERSION" >> "$GITHUB_ENV"
          echo "Используется версия: $VERSION"

      - run: |
          RAND_HASH=$(openssl rand -hex 4)
          echo "cache_id=$(date --utc '+%V')_$RAND_HASH" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}-${{ env.version }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-

      - name: Настройка Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Установка зависимостей
        run: |
          apt update
          apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev -u -y
          python -m pip install --upgrade pip
          pip install --force-reinstall --no-cache-dir -r requirements.txt
          pip install pillow cairosvg

      - name: Деплой с mike
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          VERSION="${{ env.version }}"
          mike deploy --push --update-aliases "$VERSION" latest
          mike set-default --push latest
          mkdocs gh-deploy --force
